### ISSUE TITLE
How do you use this

### ISSUE THREAD

**Issue by Neadcoolgamer1** [dragongoose/enrichingstudents-scheduler#1]
I want too use this but I don't understand what too add to make it work

**Comment by dragongoose** [comment]
Thank you for taking interest!

The instructions on how to use are said in the [README](https://github.com/dragongoose/enrichingstudents-scheduler/blob/master/readme.md) file.
What exactly are you confused on? I may be able to help you then.

**Comment by Neadcoolgamer1** [comment]
I don't understand how too set it up, I says it needs a template but I have no idea where the template should be and what kind of file it is. Also have no idea what too put in the template.

**Comment by Neadcoolgamer1** [comment]
Can you give me the command I should run please and also where to I put the token of my account?

**Comment by dragongoose** [comment]
Yes, the command needed to run is in the [README](https://github.com/dragongoose/enrichingstudents-scheduler/blob/master/readme.md).

`node index --template teacherLastName,teacherLastName,teacherLastName,teacherLastName,teacherLastName --fallback fallbackTeacher --weeks 2 --token "token"`

This is the command you should use. Put your token in the quotation marks in the token argument.
fallbackTeacher is just a different teacher to try and schedule incase the teacher in the template isn't available to be schedule.
Of course, change the weeks to the amount you would like.

**Comment by Neadcoolgamer1** [comment]
ok I will try

**Comment by Neadcoolgamer1** [comment]
![image](https://user-images.githubusercontent.com/111439540/186446910-87e92cc5-3c3a-40af-afd8-208fc06f8f43.png)

I get this

**Comment by dragongoose** [comment]
The wrong version of node-fetch was installed.
Try running `npm i` again, and if that doesn't work, run `npm install node-fetch@2`
Once you finish that, run the command again.

**Comment by Neadcoolgamer1** [comment]
I did still giving me the same error

**Comment by dragongoose** [comment]
You must have conflicting package.json files in the directory, because it's trying to run in module mode.

Please clone the repository with `git clone https://github.com/dragongoose/enrichingstudents-scheduler.git` and `cd enrichingstudents-scheduler`, or download the repo as a zip from the [the code page](https://github.com/dragongoose/enrichingstudents-scheduler).

**Comment by dragongoose** [comment]
Interesting. I just updated the program, please pull the repo again, and try again.
It should generate a log file called `debug.log` if you can send that, that would be perfect.

**Comment by Neadcoolgamer1** [comment]
[debug.log](https://github.com/dragongoose/enrichingstudents-scheduler/files/9417515/debug.log)

**Comment by dragongoose** [comment]
It seems like it cant find any available courses to schedule. Are you sure you are able to schedule on the enriching students website?

**Comment by Neadcoolgamer1** [comment]
Yes I can I tried a different teacher and still giving me the samething

**Comment by dragongoose** [comment]
I've made another update, please pull, run it again, and send the logfile.

**Comment by Neadcoolgamer1** [comment]
[debug.log](https://github.com/dragongoose/enrichingstudents-scheduler/files/9417630/debug.log)

**Comment by Neadcoolgamer1** [comment]
node index.js --template Hester,Hester,Hester,Hester,Hester --fallback Hester --weeks 1 --token "token"

**Comment by Neadcoolgamer1** [comment]
That is what I'm running

**Comment by dragongoose** [comment]
Oh, I think I know why now....
You need to replace token with your actual Enriching Students account token.
I should've asked that in the first place 🤦‍♂️

**Comment by Neadcoolgamer1** [comment]
Don't want to be sharing my token

**Comment by dragongoose** [comment]
Understandable. 
Your debug file seems a bit incorrect for what it's supposed to do, are you sure you're using the latest verison?

**Comment by Neadcoolgamer1** [comment]
[2022-08-24T12:07:56.697] [DEBUG] debug - courses []
[2022-08-24T12:08:44.204] [DEBUG] debug - courses []

**Comment by dragongoose** [comment]
My apologies, I forgot to push to changes I made. Please pull the repo again, run, and send the debug log.

**Comment by Neadcoolgamer1** [comment]
ok

**Comment by Neadcoolgamer1** [comment]
[2022-08-24T12:17:29.234] [DEBUG] debug - rawCourses{"courses":[],"courseListStatusId":4,"wasFoundInCache":false}

**Comment by dragongoose** [comment]
The API seems to not be returning any courses back when requesting and I can't reproduce this.
I'm sorry, but I wont be able to help any further.

**Comment by Neadcoolgamer1** [comment]
![image](https://user-images.githubusercontent.com/111439540/186473213-e61682cc-8d11-4f5d-8e7a-1014fffacd61.png)

This is what the website looks like for me what do I put in the teachers fill out
