### ISSUE TITLE
Cant schedule classes, TypeError: Cannot read properties of null (reading 'courseId')

### ISSUE THREAD

**Issue by Neadcoolgamer1** [dragongoose/enrichingstudents-scheduler#2]
![image](https://user-images.githubusercontent.com/111439540/186481562-169b7628-ef7b-4c12-93a7-cc8e3b4d9b33.png)

This is what our schools looks like what would I put in for teachers last name?

**Comment by dragongoose** [comment]
The last name would be the Teacher's last name. For example, in the image it says Foust, Marley. Foust would be the last name.

**Comment by Neadcoolgamer1** [comment]
![image](https://user-images.githubusercontent.com/111439540/186662826-54f8f164-4375-49dd-8034-cd4f8a0107db.png)

**Comment by Neadcoolgamer1** [comment]
It is trying to schedule me for a class this Monday even though it is past Monday is their a way to fix this?

**Comment by Neadcoolgamer1** [comment]
I think the program is trying to schedule me for a date that has already happened so I breaks. Is their any way too make it so it starts on the current date and goes from their?

**Comment by dragongoose** [comment]
Glad to see it seems to be getting further than the issue it was having before. I agree, what you suspect may be true.

Can you send your debug file?

**Comment by Neadcoolgamer1** [comment]
[debug.log](https://github.com/dragongoose/enrichingstudents-scheduler/files/9427092/debug.log)

**Comment by dragongoose** [comment]
What's the command you're using to run it? Ofc, exclude your token.

**Comment by Neadcoolgamer1** [comment]
node index.js --template Anvar,Adams,Anvar,Bentley,Balata --fallback Coots --weeks 1 --token "token"

**Comment by dragongoose** [comment]
Good news! I was able to reproduce the issue and it should now be fixed. Please pull the repo again and run.

**Comment by Neadcoolgamer1** [comment]
It seems to be working now

**Comment by dragongoose** [comment]
Nice! Glad it's working!

**Comment by dragongoose** [comment]
Reopening because I found the root cause. When courseListStatusId is 2, that means scheduling is disabled. This should probably be added later.

**Comment by dragongoose** [comment]
Done
